# Generated by Django 5.1.1 on 2026-07-18 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartera',
            name='supervisores',
            field=models.ManyToManyField(blank=True, related_name='carteras_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
