# Generated by Django 5.1.15 on 2026-07-29 03:06 (reordenada a mano)
#
# La supervision se mueve de Cartera (toda la cartera) a Subcartera (solo esa subcartera), para
# que varios supervisores puedan compartir una misma cartera (ej. "Tanner", que el reporte
# regulatorio busca por nombre exacto) sin verse los clientes entre ellos. El orden de las
# operaciones importa: agregar el campo nuevo, COPIAR los datos existentes (cada supervisor de
# una cartera pasa a supervisar TODAS sus subcarteras -- nadie pierde acceso a lo que ya veia),
# y recien ahi borrar el campo viejo. Al reves se perderia la fuente de datos antes de copiarla.
from django.conf import settings
from django.db import migrations, models


def backfill_subcartera_supervisores(apps, schema_editor):
    Cartera = apps.get_model('cartera', 'Cartera')
    for cartera in Cartera.objects.prefetch_related('supervisores', 'subcarteras').all():
        supervisores_ids = list(cartera.supervisores.values_list('pk', flat=True))
        if not supervisores_ids:
            continue
        for sub in cartera.subcarteras.all():
            sub.supervisores.add(*supervisores_ids)


def noop_reverse(apps, schema_editor):
    # No hay vuelta atras automatica: reconstruir Cartera.supervisores a partir de N subcarteras
    # con distintos supervisores es ambiguo (¿union? ¿solo si todas coinciden?). Si hace falta
    # revertir, se resuelve a mano.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_cartera_supervisores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subcartera',
            name='supervisores',
            field=models.ManyToManyField(blank=True, related_name='subcarteras_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_subcartera_supervisores, noop_reverse),
        migrations.RemoveField(
            model_name='cartera',
            name='supervisores',
        ),
    ]
