# Generated by Django 5.1.15 on 2026-07-30 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_remove_cartera_supervisores_subcartera_supervisores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartera',
            name='arbol_asignado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='arbol_asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartera',
            name='arbol_tipo',
            field=models.CharField(blank=True, choices=[('galgo', 'Galgo'), ('tanner', 'Tanner'), ('nuevo_capital', 'Nuevo Capital')], max_length=20),
        ),
    ]
