services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: turbotubo
      POSTGRES_USER: turbotubo
      POSTGRES_PASSWORD: turbotubo
    ports:
      - "5432:5432"
    volumes:
      - turbotubo_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  turbotubo_pgdata:
