# Generated by Django 5.1.15 on 2026-07-30 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('clientes', 'Clientes'), ('telefonos', 'Teléfonos'), ('email', 'Email'), ('direccion', 'Dirección'), ('bienes', 'Bienes'), ('aval', 'Aval'), ('asignaciones', 'Asignaciones'), ('gestiones', 'Gestiones'), ('suspensiones', 'Suspensiones (ciclo de vida)')], max_length=20)),
                ('archivo_nombre', models.CharField(blank=True, max_length=255)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('deshecha', 'Deshecha')], default='completada', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deshecha_at', models.DateTimeField(blank=True, null=True)),
                ('deshecha_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_masivas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga masiva',
                'verbose_name_plural': 'Cargas masivas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CargaMasivaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado')], max_length=12)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='core.cargamasiva')),
            ],
            options={
                'verbose_name': 'Cambio de carga masiva',
                'verbose_name_plural': 'Cambios de carga masiva',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_cargam_content_f837e1_idx')],
            },
        ),
    ]
