# Generated by Django 5.1.1 on 2026-07-18 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_purga_terminado', models.PositiveIntegerField(default=15, help_text='Dias despues del fin del mes en que se declaro "al dia" para purgar las gestiones de un lead terminado (se conservan las grabaciones).')),
                ('dias_purga_desasignado', models.PositiveIntegerField(default=90, help_text='Dias desde que el lead quedo desasignado para purgar sus gestiones (se conservan las grabaciones).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de retención',
                'verbose_name_plural': 'Configuración de retención',
            },
        ),
    ]
