# Generated by Django 5.1.1 on 2026-07-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspensiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionsettings',
            name='dias_retencion_statuslog',
            field=models.PositiveIntegerField(default=90, help_text='Dias que se conserva el detalle del historial de cambios de status antes de purgarlo (el "mejor status" es un campo del lead, no se pierde).'),
        ),
    ]
