# Generated by Django 5.1.1 on 2026-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspensiones', '0002_retentionsettings_dias_retencion_statuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retentionsettings',
            name='dias_purga_desasignado',
            field=models.PositiveIntegerField(default=90, help_text='Dias desde que el lead quedo desasignado para purgar sus gestiones (se conservan las grabaciones). Sujeto al mismo piso legal de 2 anios sobre las gestiones (Ley 21.320).'),
        ),
        migrations.AlterField(
            model_name='retentionsettings',
            name='dias_purga_terminado',
            field=models.PositiveIntegerField(default=15, help_text='Dias despues del fin del mes en que se declaro "al dia" para purgar las gestiones de un lead terminado (se conservan las grabaciones). Sujeto a un piso legal: las gestiones nunca se purgan antes de 2 anios desde su realizacion (Ley 21.320), aunque aqui se ponga menos.'),
        ),
    ]
