# Generated by Django 5.1.1 on 2026-07-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspensiones', '0003_alter_retentionsettings_dias_purga_desasignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionsettings',
            name='dias_retencion_accesos',
            field=models.PositiveIntegerField(default=90, help_text='Dias que se conserva el registro de accesos a datos de deudores (Configuracion -> Registros de acciones) antes de purgarlo.'),
        ),
    ]
