# Generated by Django 5.1.15 on 2026-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspensiones', '0004_retentionsettings_dias_retencion_accesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionsettings',
            name='dias_retencion_asignaciones',
            field=models.PositiveIntegerField(default=180, help_text='Dias que se conserva el historial de (re)asignaciones de leads a cobradores (LeadAssignment) antes de purgarlo. La asignacion ACTUAL vive en Lead.assigned_to, no se pierde; esto es solo el rastro historico.'),
        ),
    ]
