# Generated by Django 5.1.15 on 2026-07-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspensiones', '0005_retentionsettings_dias_retencion_asignaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionsettings',
            name='dias_retencion_compromisos_rotos',
            field=models.PositiveIntegerField(default=60, help_text='Dias que se conserva el registro de un compromiso de pago marcado como roto (actions.PaymentCommitment con motivo_retiro=roto) antes de purgarlo. El status del lead ya quedo actualizado al momento de marcarlo roto; esto es solo el rastro historico (visible en Compromisos -> Compromisos rotos).'),
        ),
    ]
