# Generated by Django 5.1.1 on 2026-07-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='supervisor',
        ),
    ]
