# Generated by Django 5.1.15 on 2026-08-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0004_cartera_arbol_asignado_at_cartera_arbol_asignado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. "cobranza-saas prod", "cobranza-saas staging".', max_length=100)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('key_prefix', models.CharField(editable=False, help_text='Primeros caracteres de la key, solo para identificarla en el admin (no sirve para autenticar).', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('carteras', models.ManyToManyField(blank=True, help_text='Carteras visibles para este cliente. Vacio = todas.', related_name='api_clients', to='cartera.cartera')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
