# Generated by Django 5.1.15 on 2026-08-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0036_reporteomegajob'),
        ('api', '0001_initial'),
        ('cartera', '0004_cartera_arbol_asignado_at_cartera_arbol_asignado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='hmac_secret_encrypted',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='WebhookEventoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'En cola'), ('procesando', 'Procesando'), ('aplicado', 'Aplicado'), ('rechazado', 'Rechazado'), ('detenido_freno', 'Detenido por freno de efectos demográficos')], default='pendiente', max_length=16)),
                ('detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='actions.action')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_eventos', to='api.apiclient')),
            ],
            options={
                'verbose_name': 'Evento de webhook',
                'verbose_name_plural': 'Eventos de webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapeoResultadoCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('carta', 'Carta'), ('ivr', 'IVR')], max_length=10)),
                ('resultado_corto', models.CharField(choices=[('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('sin_whatsapp', 'Sin WhatsApp'), ('humano_detectado', 'Humano detectado'), ('buzon_detectado', 'Buzón detectado'), ('sin_respuesta', 'Sin respuesta'), ('error_conexion', 'Error de conexión'), ('no_disponible', 'No disponible')], max_length=20)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_campana', to='cartera.cartera')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actions.medio')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='actions.resultado')),
            ],
            options={
                'verbose_name': 'Mapeo resultado campaña',
                'verbose_name_plural': 'Mapeos resultado campaña',
                'unique_together': {('cartera', 'canal', 'resultado_corto')},
            },
        ),
    ]
