# Generated by Django 5.1.1 on 2026-07-28 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0020_lead_datos_purgados_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ver_ficha', 'Vio ficha del cliente'), ('exportar_clientes', 'Exportó clientes'), ('exportar_tanner', 'Exportó reporte Tanner'), ('exportar_nuevocapital', 'Exportó reporte Nuevo Capital'), ('exportar_compromisos', 'Exportó compromisos'), ('exportar_gestiones', 'Exportó gestiones'), ('descargar_grabaciones', 'Descargó grabaciones')], max_length=32)),
                ('lead_op', models.CharField(blank=True, max_length=32)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lead.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='configuraci_timesta_159485_idx')],
            },
        ),
    ]
