# Generated by Django 5.1.15 on 2026-08-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_accesslog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action_type',
            field=models.CharField(choices=[('ver_ficha', 'Vio ficha del cliente'), ('exportar_clientes', 'Exportó clientes'), ('exportar_tanner', 'Exportó reporte Tanner'), ('exportar_tanner_omega', 'Exportó gestiones Tanner a Omega'), ('exportar_nuevocapital', 'Exportó reporte Nuevo Capital'), ('exportar_compromisos', 'Exportó compromisos'), ('exportar_gestiones', 'Exportó gestiones'), ('descargar_grabaciones', 'Descargó grabaciones'), ('freno_demografico_webhook', 'Freno de efectos demográficos activado (webhook API)')], max_length=32),
        ),
    ]
