# Generated by Django 5.1.1 on 2024-10-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographics', '0009_rename_address_avaldemographics_aval_address_and_more'),
        ('lead', '0010_alter_lead_dv'),
        ('team', '0004_alter_team_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, editable=False, max_length=16, null=True)),
                ('cartera', models.CharField(blank=True, choices=[('tanner', 'Tanner'), ('galgo', 'Galgo')], editable=False, max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone_call', 'Phone call'), ('whatsapp_call', 'WhatsApp call'), ('ivr_audio', 'IVR_audio'), ('ivr_mute', 'IVR_mute')], max_length=20, verbose_name='Action Type')),
                ('result', models.CharField(choices=[('aporta_informacion_deudor_principal', 'Aporta información deudor principal'), ('buzon_de_voz', 'Buzón de voz'), ('compromiso_de_pago', 'Compromiso de pago'), ('con_seguro_en_tramite', 'Con seguro en trámite'), ('corta_llamado', 'Corta llamado'), ('dacion', 'Dación'), ('email_invalido', 'Email inválido'), ('fono_no_corresponde', 'Fono no corresponde'), ('ivr_mudo_enviado', 'IVR mudo enviado'), ('msj_de_contacto', 'Msj de contacto'), ('msj_de_seguimiento', 'Msj de seguimiento'), ('no_responde', 'No responde'), ('pago_al_dia', 'Pago al día'), ('pago_contenido', 'Pago contenido'), ('recibe_recado', 'Recibe recado'), ('reclamo', 'Reclamo'), ('recordatorio_de_compromiso', 'Recordatorio de compromiso'), ('renegociacion', 'Renegociación'), ('responde_msj_contacto_sin_fecha', 'Responde msj contacto sin fecha'), ('sin_whatsapp', 'Sin WhatsApp'), ('solicita_llamado_posterior', 'Solicita llamado posterior'), ('telefono_congestionado', 'Teléfono congestionado'), ('volver_a_llamar', 'Volver a llamar')], max_length=255, verbose_name='Result')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('create_payment_commitment', models.BooleanField(default=False, verbose_name='Create Payment Commitment')),
                ('create_payment', models.BooleanField(default=False, verbose_name='Create Payment')),
                ('convert_debt_free', models.BooleanField(default=False, verbose_name='Convert Debt Free')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='lead.lead')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='demographics.phone')),
                ('team', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
