# Generated by Django 5.1.1 on 2026-07-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_target'),
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='cartera',
        ),
        migrations.AddField(
            model_name='action',
            name='subcartera',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.subcartera'),
        ),
    ]
