# Generated by Django 5.1.1 on 2026-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_remove_action_action_type_remove_action_result_medio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de compromiso de pago'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='requiere_fecha_pago',
            field=models.BooleanField(default=False, help_text='Si está activo, la gestión exige una fecha de compromiso/pago asociada.'),
        ),
    ]
