# Generated by Django 5.1.1 on 2026-07-14 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_pendingpbxcall_callrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='retention_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingpbxcall',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_calls', to='actions.action'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='descarga_grabacion',
            field=models.BooleanField(default=False, help_text='Si está activo, al grabar una gestión de llamada con este resultado el sistema busca y guarda la grabación de la llamada en pbxip.cl. Úsalo solo para resultados que impliquen contacto efectivo con el cliente (retención legal de 2 años).'),
        ),
    ]
