# Generated by Django 5.1.1 on 2026-07-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_callrecording_retention_until_pendingpbxcall_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='es_llamada',
            field=models.BooleanField(default=False),
        ),
    ]
