# Generated by Django 5.1.1 on 2026-07-14 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_medio_es_llamada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuario que configuró este resultado (ej. quién activó descarga_grabacion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
