# Generated by Django 5.1.1 on 2026-07-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_resultado_actualizado_por'),
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resultado',
            name='cartera',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='cartera.cartera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resultado',
            name='tipo_contacto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('cartera', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='medio',
        ),
    ]
