# Generated by Django 5.1.1 on 2026-07-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_alter_resultado_unique_together_medio_codigo_and_more'),
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('cartera', 'nombre', 'tipo_contacto')},
        ),
    ]
