# Generated by Django 5.1.1 on 2026-07-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_alter_resultado_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='monto_compromiso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Monto de compromiso'),
        ),
        migrations.AddField(
            model_name='medio',
            name='es_inbound',
            field=models.BooleanField(default=False),
        ),
    ]
