# Generated by Django 5.1.1 on 2026-07-15 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_action_monto_compromiso_medio_es_inbound'),
        ('cartera', '0001_initial'),
        ('lead', '0013_lead_fecha_compromiso_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compromiso', models.DateField(verbose_name='Fecha de compromiso')),
                ('monto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Monto')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_commitment', to='actions.action')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_commitments', to='lead.lead')),
                ('subcartera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_commitments', to='cartera.subcartera')),
            ],
            options={
                'verbose_name': 'Compromiso de pago',
                'verbose_name_plural': 'Compromisos de pago',
                'ordering': ['-fecha_compromiso', '-created_at'],
            },
        ),
    ]
