# Generated by Django 5.1.1 on 2026-07-15 21:54

from django.db import migrations, models

NOMBRES_LLAMADA_MANUAL = {'MANUAL', 'LLAMADA', 'LLAMADO', 'TELEFONICO', 'TELEFÓNICO'}


def backfill_permite_manual(apps, schema_editor):
    Medio = apps.get_model('actions', 'Medio')
    for medio in Medio.objects.all():
        nombre = (medio.nombre or '').strip().upper()
        if medio.es_inbound:
            permite = False
        elif medio.canal == 'email':
            permite = True
        elif 'WHATSAPP' in nombre:
            permite = True
        else:
            permite = nombre in NOMBRES_LLAMADA_MANUAL
        if medio.permite_manual != permite:
            medio.permite_manual = permite
            medio.save(update_fields=['permite_manual'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_paymentcommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='permite_manual',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_permite_manual, noop),
    ]
