# Generated by Django 5.1.1 on 2026-07-16 20:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_medio_permite_manual'),
        ('cartera', '0001_initial'),
        ('lead', '0014_leadnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha de pago')),
                ('tipo', models.CharField(choices=[('pie', 'Pie'), ('cuota', 'Cuota')], default='cuota', max_length=10, verbose_name='Tipo')),
                ('comprobante', models.FileField(blank=True, help_text='Imagen (PNG/JPG) o PDF del comprobante de pago.', null=True, upload_to='payment_receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lead.lead')),
                ('subcartera', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cartera.subcartera')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
