# Generated by Django 5.1.1 on 2026-07-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='efecto_pago',
            field=models.CharField(blank=True, choices=[('', 'No aplica'), ('pagando', 'Pagando'), ('al_dia', 'Al día')], max_length=10),
        ),
    ]
