# Generated by Django 5.1.1 on 2026-07-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_fix_status_flags_galgo_tanner_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='desactiva_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultado',
            name='efecto_demografia',
            field=models.CharField(blank=True, choices=[('', 'No aplica'), ('no_existe', 'Marca "No existe"'), ('fuera_servicio', 'Marca "Fuera de servicio"'), ('blacklist', 'Blacklist')], max_length=15),
        ),
    ]
