# Generated by Django 5.1.1 on 2026-07-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_seed_efecto_demografia_final'),
        ('lead', '0018_lead_desasignado_at_lead_motivo_suspension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_recordings', to='lead.lead'),
        ),
    ]
