# Generated by Django 5.1.1 on 2026-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0021_alter_callrecording_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='cartera_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='lead_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='op_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
