# Generated by Django 5.1.15 on 2026-07-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0022_callrecording_cartera_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='sin_audio_detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='sin_audio_motivo',
            field=models.CharField(blank=True, choices=[('descarga_fallida', 'Se encontró el registro en pbxip.cl pero no se pudo descargar el audio'), ('sin_match', 'No se encontró un registro de llamada que coincida'), ('error_api', 'La central telefónica no respondió')], max_length=20),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='call_recordings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='cdr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
