# Generated by Django 5.1.15 on 2026-07-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0023_callrecording_sin_audio_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpbxcall',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
