# Generated by Django 5.1.15 on 2026-07-30 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0024_pendingpbxcall_last_attempt_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabacionesExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(upload_to='exports/grabaciones/entrada/%Y/%m/')),
                ('archivo', models.FileField(blank=True, upload_to='exports/grabaciones/salida/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'En cola'), ('procesando', 'Procesando'), ('listo', 'Listo para descargar'), ('vacio', 'Sin grabaciones'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('total', models.PositiveIntegerField(default=0)),
                ('errores', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs_grabaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export de grabaciones',
                'verbose_name_plural': 'Exports de grabaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
