# Generated by Django 5.1.15 on 2026-07-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_grabacionesexportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='motivo_retiro',
            field=models.CharField(blank=True, choices=[('editado', 'Editado (se acordó fecha/monto nuevo)'), ('roto', 'Compromiso roto (no se cumplió)')], max_length=10),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='reemplazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='actions.paymentcommitment'),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='retirado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='retirado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
