# Generated by Django 5.1.15 on 2026-07-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0026_paymentcommitment_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
    ]
