# Generated by Django 5.1.15 on 2026-07-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0027_payment_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='comentario_retiro',
            field=models.TextField(blank=True),
        ),
    ]
