# Generated by Django 5.1.15 on 2026-07-31 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0028_paymentcommitment_comentario_retiro'),
        ('cartera', '0004_cartera_arbol_asignado_at_cartera_arbol_asignado_por_and_more'),
        ('demographics', '0013_email'),
        ('lead', '0022_alter_lead_created_by_and_more'),
        ('team', '0007_alter_team_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['-created_at'], name='action_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['lead', '-created_at'], name='action_lead_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['subcartera', '-created_at'], name='action_subcart_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['user', '-created_at'], name='action_user_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-fecha'], name='pago_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcommitment',
            index=models.Index(fields=['vigente', '-fecha_compromiso'], name='pc_vigente_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcommitment',
            index=models.Index(fields=['lead', 'vigente'], name='pc_lead_vigente_idx'),
        ),
    ]
