# Generated by Django 5.1.15 on 2026-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0029_action_action_creado_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='permite_manual',
            field=models.BooleanField(default=True),
        ),
    ]
