# Generated by Django 5.1.15 on 2026-08-07 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0031_tanner_pac_venta_directa_no_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaGestionesJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(upload_to='cargas/gestiones/entrada/%Y/%m/')),
                ('archivo_errores', models.FileField(blank=True, upload_to='cargas/gestiones/errores/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'En cola'), ('procesando', 'Procesando'), ('listo', 'Cargada'), ('con_errores', 'Se encontraron errores'), ('error', 'Falla del servidor')], default='pendiente', max_length=12)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('creadas', models.PositiveIntegerField(default=0)),
                ('omitidas_duplicadas', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_gestiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de gestiones',
                'verbose_name_plural': 'Cargas de gestiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
