# Generated by Django 5.1.15 on 2026-08-07 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0032_cargagestionesjob'),
        ('cartera', '0004_cartera_arbol_asignado_at_cartera_arbol_asignado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTannerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('archivo', models.FileField(blank=True, upload_to='reportes/tanner/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'En cola'), ('procesando', 'Procesando'), ('listo', 'Listo para descargar'), ('vacio', 'Sin gestiones en el rango'), ('error', 'Falla del servidor')], default='pendiente', max_length=12)),
                ('total_gestiones', models.PositiveIntegerField(default=0)),
                ('dias_con_datos', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_tanner', to=settings.AUTH_USER_MODEL)),
                ('subcartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cartera.subcartera')),
            ],
            options={
                'verbose_name': 'Reporte Tanner por rango',
                'verbose_name_plural': 'Reportes Tanner por rango',
                'ordering': ['-created_at'],
            },
        ),
    ]
