# Generated by Django 5.1.15 on 2026-08-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0033_reportetannerjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='origen',
            field=models.CharField(choices=[('saliente', 'Nosotros contactamos'), ('entrante', 'El cliente nos contactó')], default='saliente', help_text='Quién inició el contacto. Lo exige el reporte de Tanner.', max_length=10, verbose_name='Origen de la gestión'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='siempre_entrante',
            field=models.BooleanField(default=False, help_text='Marca este resultado como una respuesta del cliente: la gestión se reporta como entrante (inbound) aunque el gestor no lo indique. Úsalo solo en resultados que no pueden ocurrir sin que el cliente conteste.'),
        ),
    ]
