# Generated by Django 5.1.15 on 2026-08-15 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0035_marcar_resultados_entrantes_tanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteOmegaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(blank=True, upload_to='reportes/omega/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'En cola'), ('procesando', 'Procesando'), ('listo', 'Listo para descargar'), ('vacio', 'Sin gestiones de Tanner ese día'), ('error', 'Falla del servidor')], default='pendiente', max_length=12)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('total_excluidas', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_omega', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Tanner a Omega',
                'verbose_name_plural': 'Reportes Tanner a Omega',
                'ordering': ['-created_at'],
            },
        ),
    ]
