# Generated by Django 5.1.15 on 2026-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0036_reporteomegajob'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='origen_masivo',
            field=models.BooleanField(default=False, help_text='Gestión creada por un envío de campaña (SMS/email/WhatsApp), no por un gestor humano.', verbose_name='Origen masivo'),
        ),
    ]
