# Generated by Django 5.1.15 on 2026-08-18 16:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0037_action_origen_masivo'),
        ('cartera', '0004_cartera_arbol_asignado_at_cartera_arbol_asignado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAutomaticoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('estandar', 'Estándar (regulatorio)'), ('generico', 'Genérico')], default='generico', max_length=12)),
                ('periodicidad', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('cada_x_dias', 'Cada X días')], default='diaria', max_length=12)),
                ('cada_x_dias', models.PositiveSmallIntegerField(default=1)),
                ('saltar_fines_de_semana', models.BooleanField(default=False, help_text='No enviar sábado ni domingo, aunque la periodicidad indique que corresponde.')),
                ('hora_envio', models.TimeField(default=datetime.time(8, 0), help_text='Hora local (America/Santiago) de envío.')),
                ('destinatarios_to', models.TextField(help_text='Emails separados por coma. Ej: data@cliente.com')),
                ('destinatarios_cc', models.TextField(blank=True)),
                ('destinatarios_cco', models.TextField(blank=True, help_text='Con copia oculta -- ej. dueños o supervisores que quieren registro sin que el resto lo sepa.')),
                ('metodo_envio', models.CharField(choices=[('smtp', 'SMTP (casilla propia)'), ('azure_acs', 'Azure Communication Services (próximamente)')], default='smtp', max_length=12)),
                ('remitente_from', models.EmailField(blank=True, help_text='Vacío = usa el remitente por defecto del sistema.', max_length=254)),
                ('asunto_personalizado', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ultima_ejecucion_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_envio_ok_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_estado', models.CharField(blank=True, choices=[('ok', 'Enviado'), ('error', 'Error'), ('sin_datos', 'Sin gestiones en el rango')], max_length=10)),
                ('ultimo_mensaje', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_automaticos', to='cartera.cartera')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_automaticos_creados', to=settings.AUTH_USER_MODEL)),
                ('subcarteras', models.ManyToManyField(blank=True, related_name='reportes_automaticos', to='cartera.subcartera')),
            ],
            options={
                'verbose_name': 'Reporte automático',
                'verbose_name_plural': 'Reportes automáticos',
                'ordering': ['-created_at'],
            },
        ),
    ]
