# Generated by Django 5.1.1 on 2026-07-20 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0002_cartera_supervisores'),
        ('lead', '0018_lead_desasignado_at_lead_motivo_suspension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloVidaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_token', models.UUIDField(db_index=True)),
                ('cartera_token', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exportado_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo_transicion', models.CharField(choices=[('suspendido', 'Suspendido'), ('desasignado', 'Desasignado'), ('reactivado', 'Reactivado'), ('terminado', 'Terminado')], max_length=15)),
                ('dias_desde_creacion_lead', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GestionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_token', models.UUIDField(db_index=True)),
                ('cartera_token', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exportado_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cobrador_token', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('secuencia', models.PositiveIntegerField(help_text='N-esima gestion de este lead (1 = la primera).')),
                ('dias_desde_creacion_lead', models.IntegerField()),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0=lunes .. 6=domingo')),
                ('dia_del_mes', models.PositiveSmallIntegerField()),
                ('franja_horaria', models.CharField(choices=[('madrugada', 'Madrugada (0-6h)'), ('manana', 'Mañana (6-12h)'), ('tarde', 'Tarde (12-18h)'), ('noche', 'Noche (18-24h)')], max_length=10)),
                ('canal', models.CharField(max_length=10)),
                ('es_llamada', models.BooleanField()),
                ('es_inbound', models.BooleanField()),
                ('target', models.CharField(blank=True, max_length=10)),
                ('contactabilidad', models.CharField(blank=True, max_length=15)),
                ('tipo_contacto', models.CharField(blank=True, max_length=50)),
                ('crea_compromiso', models.BooleanField()),
                ('requiere_fecha_pago', models.BooleanField()),
                ('efecto_pago', models.CharField(blank=True, max_length=10)),
                ('dias_hasta_compromiso', models.IntegerField(blank=True, null=True)),
                ('status_antes', models.CharField(max_length=20)),
                ('status_despues', models.CharField(max_length=20)),
                ('ciclo_cartera', models.CharField(max_length=20)),
                ('ciclo', models.CharField(max_length=20)),
                ('tipo_cobranza', models.CharField(max_length=20)),
                ('tiene_aval', models.CharField(max_length=2)),
                ('saldo_insoluto', models.IntegerField()),
                ('cuotas_atrasadas', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_token', models.UUIDField(db_index=True)),
                ('cartera_token', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exportado_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('monto', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('dia_del_mes', models.PositiveSmallIntegerField()),
                ('dias_desde_ultima_gestion', models.IntegerField(blank=True, null=True)),
                ('dias_vs_compromiso', models.IntegerField(blank=True, help_text='Negativo = pago antes del compromiso, positivo = despues, null = sin compromiso previo.', null=True)),
                ('status_antes', models.CharField(blank=True, max_length=20)),
                ('status_despues', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarteraPseudonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pseudonimo_ml', to='cartera.cartera')),
            ],
        ),
        migrations.CreateModel(
            name='CobradorPseudonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pseudonimo_ml', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadPseudonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pseudonimo_ml', to='lead.lead')),
            ],
        ),
    ]
