# Generated by Django 5.1.1 on 2024-10-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0009_leadassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('inmueble', 'Inmueble'), ('otro', 'Otro')], max_length=255)),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('año', models.IntegerField(blank=True, max_length=4, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
            ],
        ),
    ]
