# Generated by Django 5.1.1 on 2024-10-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_status', models.CharField(blank=True, choices=[('active', 'Active'), ('non-existent', 'Non-existent'), ('out of service', 'Out of service'), ('blacklisted', 'Blacklisted')], max_length=255)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics.iditem')),
            ],
        ),
    ]
