# Generated by Django 5.1.1 on 2024-10-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_phone'),
        ('lead', '0009_leadassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iditem',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='id_item',
        ),
        migrations.CreateModel(
            name='IDDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics.iditem')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('phones', models.ManyToManyField(blank=True, related_name='id_demographics', to='demographics.phone')),
            ],
        ),
    ]
