# Generated by Django 5.1.1 on 2024-10-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0003_remove_iditem_lead_remove_phone_id_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iditem',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
