# Generated by Django 5.1.1 on 2024-10-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0004_alter_iditem_año'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvalDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aval', models.CharField(max_length=255)),
                ('rut_aval', models.CharField(max_length=10)),
                ('dv_aval', models.CharField(max_length=1)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('id_demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics.iddemographics', unique=True)),
                ('phones', models.ManyToManyField(blank=True, related_name='aval_demographics', to='demographics.phone')),
            ],
        ),
    ]
