# Generated by Django 5.1.1 on 2024-10-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0005_avaldemographics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaldemographics',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='iddemographics',
            name='phones',
        ),
        migrations.AddField(
            model_name='avaldemographics',
            name='aval_phones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'phone_type': 'aval'}, related_name='aval_demographics_aval_phone', to='demographics.phone'),
        ),
        migrations.AddField(
            model_name='iddemographics',
            name='principal_phones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'phone_type': 'principal'}, related_name='id_demographics_principal_phone', to='demographics.phone'),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('principal', 'Principal'), ('aval', 'Aval')], default='principal', max_length=255),
        ),
        migrations.AlterField(
            model_name='iditem',
            name='item_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('inmueble', 'Inmueble'), ('otro', 'Otro')], default='auto', max_length=255),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number_status',
            field=models.CharField(choices=[('active', 'Active'), ('non-existent', 'Non-existent'), ('out of service', 'Out of service'), ('blacklisted', 'Blacklisted')], default='active', max_length=255),
        ),
    ]
