# Generated by Django 5.1.1 on 2024-10-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0006_remove_avaldemographics_phones_and_more'),
        ('lead', '0009_leadassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iddemographics',
            name='id_item',
        ),
        migrations.AddField(
            model_name='iditem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
        migrations.AlterField(
            model_name='avaldemographics',
            name='id_demographics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demographics.iddemographics'),
        ),
        migrations.AlterField(
            model_name='iddemographics',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
    ]
