# Generated by Django 5.1.1 on 2024-10-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0007_remove_iddemographics_id_item_iditem_lead_and_more'),
        ('lead', '0009_leadassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
    ]
