# Generated by Django 5.1.1 on 2024-11-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0009_rename_address_avaldemographics_aval_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaldemographics',
            name='aval_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaldemographics',
            name='aval_dv',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='avaldemographics',
            name='aval_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
