# Generated by Django 5.1.1 on 2026-07-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0011_alter_avaldemographics_aval_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaldemographics',
            name='aval_email_status',
            field=models.CharField(choices=[('active', 'Activo'), ('non-existent', 'No existe'), ('out of service', 'Fuera de servicio'), ('blacklisted', 'Blacklist')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='iddemographics',
            name='principal_email_status',
            field=models.CharField(choices=[('active', 'Activo'), ('non-existent', 'No existe'), ('out of service', 'Fuera de servicio'), ('blacklisted', 'Blacklist')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='phone',
            name='whatsapp_activo',
            field=models.BooleanField(default=True),
        ),
    ]
