# Generated by Django 5.1.1 on 2026-07-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0012_avaldemographics_aval_email_status_and_more'),
        ('lead', '0020_lead_datos_purgados_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('email_status', models.CharField(choices=[('active', 'Activo'), ('non-existent', 'No existe'), ('out of service', 'Fuera de servicio'), ('blacklisted', 'Blacklist')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='lead.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
