# Generated by Django 5.1.15 on 2026-08-07 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0013_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefonos', 'Teléfonos'), ('correos', 'Correos')], max_length=10)),
                ('filtros', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='exports/demografia/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'En cola'), ('procesando', 'Procesando'), ('listo', 'Listo para descargar'), ('vacio', 'Sin datos con esos filtros'), ('error', 'Falla del servidor')], default='pendiente', max_length=12)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports_contactos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export de contactos',
                'verbose_name_plural': 'Exports de contactos',
                'ordering': ['-created_at'],
            },
        ),
    ]
