# Generated by Django 5.1.1 on 2026-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_pbx_email_userprofile_pbx_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
