# Generated by Django 5.1.1 on 2024-10-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_leadassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='dv',
            field=models.CharField(max_length=255),
        ),
    ]
