# Generated by Django 5.1.1 on 2026-07-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
        ('lead', '0011_statuschangelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='cartera',
        ),
        migrations.AddField(
            model_name='lead',
            name='subcartera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='cartera.subcartera'),
            preserve_default=False,
        ),
    ]
