# Generated by Django 5.1.1 on 2026-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_remove_lead_cartera_lead_subcartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fecha_compromiso_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
