# Generated by Django 5.1.1 on 2026-07-16 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_leadnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
