# Generated by Django 5.1.1 on 2026-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_lead_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estado_judicial',
            field=models.CharField(choices=[('sin_informacion', 'Sin información'), ('sin_accion_judicial', 'Sin acción judicial'), ('ingreso_demanda', 'Ingreso demanda'), ('busquedas_negativas', 'Búsquedas negativas'), ('busquedas_positivas', 'Búsquedas positivas'), ('notificado', 'Notificado'), ('embargado', 'Embargado'), ('oficio', 'Oficio'), ('incautado', 'Incautado'), ('rematado', 'Rematado')], default='sin_informacion', max_length=25),
        ),
    ]
