# Generated by Django 5.1.1 on 2026-07-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_lead_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted_to_client',
        ),
    ]
