# Generated by Django 5.1.1 on 2026-07-18 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_status_historico_from_status(apps, schema_editor):
    """Los leads ya existentes no deben perder terreno ya ganado: su historico parte igual
    a su status actual (en vez de "recien asignado", el default para leads nuevos)."""
    Lead = apps.get_model('lead', 'Lead')
    Lead.objects.exclude(status='recien asignado').update(status_historico=models.F('status'))


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_remove_lead_converted_to_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status_historico',
            field=models.CharField(choices=[('recien asignado', 'Recién asignado'), ('inubicable', 'Inubicable'), ('no contactado', 'No contactado'), ('contactado', 'Contactado'), ('compromiso', 'Compromiso de pago'), ('compromiso roto', 'Compromiso roto'), ('pagando', 'Pagando'), ('al dia', 'Al dia')], default='recien asignado', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('recien asignado', 'Recién asignado'), ('inubicable', 'Inubicable'), ('no contactado', 'No contactado'), ('contactado', 'Contactado'), ('compromiso', 'Compromiso de pago'), ('compromiso roto', 'Compromiso roto'), ('pagando', 'Pagando'), ('al dia', 'Al dia')], default='recien asignado', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_status_historico_from_status, migrations.RunPython.noop),
    ]
