# Generated by Django 5.1.1 on 2026-07-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_lead_status_historico_alter_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='desasignado_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='motivo_suspension',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='suspendido_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='terminado_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='activo',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('terminado', 'Terminado'), ('desasignado', 'Desasignado')], default='activo', max_length=255),
        ),
    ]
