# Generated by Django 5.1.1 on 2026-07-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0018_lead_desasignado_at_lead_motivo_suspension_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
