# Generated by Django 5.1.1 on 2026-07-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0019_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='datos_purgados_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
