# Generated by Django 5.1.15 on 2026-07-29 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_lead_datos_purgados_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfile',
            name='file',
            field=models.FileField(upload_to='leadfiles/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf', 'mp3'])]),
        ),
    ]
