# Generated by Django 5.1.15 on 2026-07-31 14:28

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_cartera_arbol_asignado_at_cartera_arbol_asignado_por_and_more'),
        ('lead', '0022_alter_lead_created_by_and_more'),
        ('team', '0007_alter_team_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='lead_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['activo'], name='lead_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['subcartera', 'status'], name='lead_subcart_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'activo'], name='lead_asignado_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(django.db.models.functions.text.Upper('op'), name='lead_op_upper_idx'),
        ),
        migrations.AddIndex(
            model_name='statuschangelog',
            index=models.Index(fields=['timestamp'], name='statuslog_ts_idx'),
        ),
    ]
