# Generated by Django 5.1.15 on 2026-08-18 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0023_lead_lead_status_idx_lead_lead_activo_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alerted_by',
            field=models.ManyToManyField(blank=True, related_name='alert_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
