"""
Django settings for turbotubo project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Trigger GitHub Actions
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False (seguro); en local se activa explicitamente con DEBUG=True en .env
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# En producción DEBE venir de una variable de entorno. Si falta y DEBUG=True (dev local)
# se usa un valor fijo solo para no romper el flujo de desarrollo; si falta y DEBUG=False
# (producción), preferimos que el deploy falle fuerte a que corra con una key insegura.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-ck8eajs$_ad62mmlo5(vsu(_l0t34*a=a&@tg(p4#!3c0$pbe_'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY debe estar definido en el entorno cuando DEBUG=False (producción).'
        )

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'index'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'actions',
    'cartera',
    'configuracion',
    'core',
    'dashboard',
    'demographics',
    'django_celery_beat',
    'lead',
    'mlmetadata',
    'suspensiones',
    'team',
    'userprofile',
  #  'schema_graph',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Comprime el HTML dinamico (~70% mas liviano). Va arriba para comprimir la respuesta ya
    # armada. Salta lo que ya viene comprimido (estaticos de WhiteNoise) y los binarios. El
    # riesgo teorico BREACH (gzip+HTTPS) lo mitiga el token CSRF enmascarado de Django.
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Obliga a cambiar la clave temporal en el primer ingreso (va DESPUES de Authentication,
    # que es quien pone request.user).
    'userprofile.middleware.ForcePasswordChangeMiddleware',
    # Evita cachear el HTML autenticado (fuga por el boton Atras tras logout). Solo HTML: no
    # toca el cache de los estaticos.
    'core.middleware.NoStoreAuthenticatedMiddleware',
]

# Allow same-origin framing so the "crear accion" popup (iframe inside a <dialog>) can load.
# Django's default is DENY, which blocks framing even from pages on this same site.
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Fernet key used to encrypt/decrypt per-user PBX (pbxip.cl) passwords at rest.
PBX_ENCRYPTION_KEY = os.environ.get('PBX_ENCRYPTION_KEY', '')

# Cuenta MAESTRA de pbxip.cl: si esta configurada, UNA sola cuenta (admin) hace todas las
# consultas y descargas al API, y los usuarios solo necesitan su EXTENSION cargada (no su
# password). Si no esta configurada, el sistema cae al modo por-usuario (cada uno con sus
# credenciales). Se deja en el entorno, nunca en el codigo.
PBX_MASTER_EMAIL = os.environ.get('PBX_MASTER_EMAIL', '')
PBX_MASTER_PASSWORD = os.environ.get('PBX_MASTER_PASSWORD', '')

# Dominio SIP de pbxip.cl (el mismo que cada cobrador tiene configurado en su Zoiper). Es el
# INTERRUPTOR entre los dos modos de marcado:
#   - VACIO (default): modo central. El backend le pide a pbxip que timbre el anexo del cobrador
#     y, al contestar, lo puentee con el cliente (dos patas: primero suena tu propio telefono).
#   - CON VALOR: modo Zoiper directo. El navegador le pasa un URI `sip:<destino>@<dominio>` al
#     softphone y Zoiper marca de una (una sola pata). El backend NO origina nada, solo registra
#     el PendingPbxCall para que el sync de grabaciones sepa que debe buscarla despues.
# En ambos modos la grabacion se cruza igual: find_matching_cdr (actions/pbx_matching.py) matchea
# por src_extension + destino + ventana de tiempo, no por como se origino la llamada.
# Cambiar esta variable NO requiere redeploy, solo reiniciar la app -- sirve de kill switch.
PBX_SIP_DOMAIN = os.environ.get('PBX_SIP_DOMAIN', '')

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
# Sin backend de resultados: el codigo nunca lee el retorno/estado de una tarea (no hay
# AsyncResult.get()/.ready()/.state en ningun lado), asi que guardarlos era puro overhead que
# ocupaba memoria del nodo Redis (el mas caro por MB de la arquitectura). task_ignore_result
# evita ademas que las tareas intenten escribir un resultado que nadie va a consultar.
CELERY_RESULT_BACKEND = None
CELERY_TASK_IGNORE_RESULT = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TIMEZONE = 'America/Santiago'

# Cache compartido entre workers (Redis, mismo host que Celery). Necesario para que el throttle
# de login (userprofile/forms.py) funcione de verdad en produccion: con el cache en memoria
# por-proceso (default de Django) cada worker de gunicorn lleva su propio contador y el limite se
# evade solo repartiendo requests entre workers.
#
# OJO con la DB: en local se usa la /1 para no mezclar claves con la cola de Celery (/0), pero
# Azure Managed Redis (Redis Enterprise) NO soporta multiples DBs -- solo existe la 0, y pedir la
# /1 falla con "DB index is out of range", dejando el cache muerto y el throttle de login
# silenciosamente desactivado. Por eso en Azure hay que apuntar CACHE_REDIS_URL a la /0; el
# KEY_PREFIX mantiene la separacion logica que antes daba la DB aparte (las claves de Celery son
# 'celery*', '_kombu.*', 'unacked*' -- no chocan con 'ttcache:...').
_redis_base = CELERY_BROKER_URL.rsplit('/', 1)[0]
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('CACHE_REDIS_URL', f'{_redis_base}/1'),
        'KEY_PREFIX': 'ttcache',
    }
}

# Cuantos dias se conserva el detalle de StatusChangeLog antes de purgarlo (tarea
# purge_status_change_log). El "mejor status" NO vive aca (es un campo del lead), asi que
# purgar el log no pierde informacion de negocio. Politica definida: 3 meses.
STATUSLOG_RETENTION_DAYS = int(os.environ.get('STATUSLOG_RETENTION_DAYS', '90'))

# Tope del cuerpo NO-archivo de un request (campos de formulario). Django excluye los archivos
# multipart de este conteo, asi que el tope real de los Excel de carga vive en core.bulk_upload
# (MAX_UPLOAD_BYTES) y el de los adjuntos en lead.models.LeadFile. Esto cubre el resto del body.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB

ROOT_URLCONF = 'turbotubo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'team.context_processors.active_team',
                'core.context_processors.asset_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'turbotubo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'turbotubo'),
        'USER': os.environ.get('DB_USER', 'turbotubo'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'turbotubo'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        # Resiliencia de conexion:
        # - CONN_MAX_AGE: reutiliza conexiones (mas rapido que abrir una por request).
        # - CONN_HEALTH_CHECKS: Django detecta una conexion muerta y la recrea en vez de fallar
        #   (clave si la BD se reinicia/duerme, como pasa con el contenedor local).
        # - connect_timeout: no colgarse indefinidamente si la BD no responde -- falla rapido.
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '5')),
        },
    }
}

# Conexion de SOLO LECTURA a la base de datos vieja (turbotubobeta en Azure), usada unicamente
# por los comandos de migracion de datos (manage.py inspeccionar_legacy). Se activa solo si
# LEGACY_DB_HOST esta definido en el entorno -- nunca se commitea una credencial real. sslmode
# require porque Azure Postgres lo exige.
if os.environ.get('LEGACY_DB_HOST'):
    DATABASES['legacy'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('LEGACY_DB_NAME', 'turbotubobeta-database'),
        'USER': os.environ.get('LEGACY_DB_USER', ''),
        'PASSWORD': os.environ.get('LEGACY_DB_PASSWORD', ''),
        'HOST': os.environ.get('LEGACY_DB_HOST', ''),
        'PORT': os.environ.get('LEGACY_DB_PORT', '5432'),
        'CONN_MAX_AGE': 0,
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '5')),
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Nivel INFO en produccion (DEBUG en local via .env): a nivel DEBUG cada query/request queda
# en el log y en Azure (disco acotado del App Service) un FileHandler sin rotacion llena el
# disco y tumba la app. RotatingFileHandler limita el tamano total a 5 archivos x 10MB (50MB).
#
# 'console' (stdout) ademas del archivo: el disco de un App Service Linux es efimero (se pierde
# en cada deploy/restart/scale-out) y el Log Stream / Application Insights de Azure capturan
# stdout/stderr del proceso, NO un archivo en ese disco -- sin esto, un error en produccion
# quedaba en un archivo que nadie llega a ver hasta entrar por SSH al contenedor.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'django_debug.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,  # sin esto, duplica cada linea via el logger raiz de abajo
        },
        # Logger raiz: cubre los loggers propios del proyecto (actions.tasks, actions.views,
        # mlmetadata.tasks, etc., todos con logging.getLogger(__name__)), que sin esto solo
        # imprimian WARNING+ a stderr y nunca quedaban en el archivo.
        '': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}