name: Build and deploy Python app to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'  # Match Azure's Python version
  DJANGO_SETTINGS_MODULE: turbotubo.deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-warn-script-location
          pip freeze > deployed_requirements.txt  # Create deployment manifest

      - name: Upload requirements snapshot
        uses: actions/upload-artifact@v4
        with:
          name: python-dependencies
          path: deployed_requirements.txt

      - name: Collect static files
        run: python manage.py collectstatic --noinput
        env:
          SECRET: ${{ secrets.SECRET }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'turbotubobeta'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .